-- Retired before production application on 2026-08-15.
--
-- The original version of this migration inserted fixed Cupro resource UUIDs
-- and legacy `cupro-reaktif-boyama/v1-0/...` Storage paths.
-- Production migration history confirms this version was never applied.
--
-- Cupro files now use the standard site resource catalog and the protected
-- Super Admin upload flow. Uploads create/update public.resources by catalog
-- slug and store files under:
--   catalog/<resource-slug>/<canonical-filename>
--
-- This migration intentionally performs no data mutation so a future
-- `supabase db push` cannot create duplicate legacy Cupro resource records.
select 1;
